// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAIRYO5qddirss8mSqAxbmmHpvOPql44w',
    appId: '1:356146410774:web:57d764c7107af5a1648c37',
    messagingSenderId: '356146410774',
    projectId: 'fluffy-friend-1ba26',
    authDomain: 'fluffy-friend-1ba26.firebaseapp.com',
    storageBucket: 'fluffy-friend-1ba26.firebasestorage.app',
    measurementId: 'G-BMEQ5J7M70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTgOVUQ5r10lEcCs0MAXJMm6wIRkk_L-s',
    appId: '1:160986468177:android:f3dfe2720132f44f5a4d70',
    messagingSenderId: '160986468177',
    projectId: 'fluffy-friend-1ba26',
    storageBucket: 'fluffy-friend-1ba26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd9dYUNaClZh9FwBbwwiynwScCF7y50hA',
    appId: '1:356146410774:ios:55372952557e3dfd648c37',
    messagingSenderId: '356146410774',
    projectId: 'fluffy-friend-e7994',
    storageBucket: 'fluffy-friend-e7994.firebasestorage.app',
    iosBundleId: 'com.example.ffApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd9dYUNaClZh9FwBbwwiynwScCF7y50hA',
    appId: '1:356146410774:ios:55372952557e3dfd648c37',
    messagingSenderId: '356146410774',
    projectId: 'fluffy-friend-e7994',
    storageBucket: 'fluffy-friend-e7994.firebasestorage.app',
    iosBundleId: 'com.example.ffApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAIRYO5qddirss8mSqAxbmmHpvOPql44w',
    appId: '1:356146410774:web:9291195bf18d9ab5648c37',
    messagingSenderId: '356146410774',
    projectId: 'fluffy-friend-e7994',
    authDomain: 'fluffy-friend-e7994.firebaseapp.com',
    storageBucket: 'fluffy-friend-e7994.firebasestorage.app',
    measurementId: 'G-K1R1W7HMFR',
  );
}
